### ISSUE TITLE
Settings page doesn't work in 2021.1.2

### ISSUE THREAD

**Issue by ForNeVeR** [Socolin/NSubstituteComplete#1]
When trying to open the unit testing settings in Rider 2021.1.2, the following exception is thrown:

```
Component ReSharperPlugin.NSubstituteComplete.Options.NSubstituteCompleteOptionPage [Singleton, Corrupted] construction has failed. Exception has been thrown by the target of an invocation. Method 'GetNewEntry' in type 'ReSharperPlugin.NSubstituteComplete.Options.MockAliasesModel' from assembly 'ReSharperPlugin.NSubstituteComplete, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

--- EXCEPTION #1/4 [TypeLoadException]
Message = “Method 'GetNewEntry' in type 'ReSharperPlugin.NSubstituteComplete.Options.MockAliasesModel' from assembly 'ReSharperPlugin.NSubstituteComplete, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.”
ExceptionPath = Root.InnerException.InnerException.InnerException
ClassName = System.TypeLoadException
Data.ThreadLocalDebugInfo = CreateAutomationForOptionsPage
HResult = COR_E_TYPELOAD=80131522
Source = ReSharperPlugin.NSubstituteComplete
TypeLoadClassName = ReSharperPlugin.NSubstituteComplete.Options.MockAliasesModel
TypeLoadAssemblyName = “ReSharperPlugin.NSubstituteComplete, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”
TypeLoadMessageArg = GetNewEntry
TypeLoadResourceID = 6012
StackTraceString = “
  at ReSharperPlugin.NSubstituteComplete.Options.NSubstituteCompleteOptionPage.MockAliases(Lifetime lifetime, OptionsSettingsSmartContext smartContext, OptionsPageContext pageContext, IconHostBase iconHost, IShellLocks locks, ISolution solution)
     at ReSharperPlugin.NSubstituteComplete.Options.NSubstituteCompleteOptionPage..ctor(Lifetime lifetime, OptionsPageContext optionsPageContext, OptionsSettingsSmartContext optionsSettingsSmartContext, OptionsSettingsSmartContext smartContext, OptionsPageContext pageContext, IconHostBase iconHost, IShellLocks locks, ISolution solution, Boolean wrapInScrollablePanel) in /home/socolin/RiderProjects/NSubstituteComplete/src/dotnet/ReSharperPlugin.NSubstituteComplete/Options/NSubstituteCompleteOptionPage.cs:line 47
”

--- Outer ---

--- EXCEPTION #2/4 [TargetInvocationException]
Message = “Exception has been thrown by the target of an invocation.”
ExceptionPath = Root.InnerException.InnerException
ClassName = System.Reflection.TargetInvocationException
Data.ThreadLocalDebugInfo = CreateAutomationForOptionsPage
InnerException = “Exception #1 at Root.InnerException.InnerException.InnerException”
HResult = COR_E_TARGETINVOCATION=80131604
Source = System.Private.CoreLib
StackTraceString = “
  at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at JetBrains.Application.Components.SingletonTypeComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
     at JetBrains.Application.Components.SingletonTypeComponentDescriptor.CreateInstance(IValueResolveContext context)
     at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
     at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.InitializationStrategyDefault.Schedule(Lifetime lifetime, ICollection`1 dscs, IComponentContainer container)
”

--- Outer ---

--- EXCEPTION #3/4 [TargetInvocationException]
Message = “Component ReSharperPlugin.NSubstituteComplete.Options.NSubstituteCompleteOptionPage [Singleton, Corrupted] construction has failed.”
ExceptionPath = Root.InnerException
ClassName = System.Reflection.TargetInvocationException
InnerException = “Exception #2 at Root.InnerException.InnerException”
HResult = COR_E_TARGETINVOCATION=80131604

--- Outer ---

--- EXCEPTION #4/4 [LoggerException]
Message = “Component ReSharperPlugin.NSubstituteComplete.Options.NSubstituteCompleteOptionPage [Singleton, Corrupted] construction has failed.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #3 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.LoggerBase.Log(LoggingLevel level, String message, Exception ex)
     at JetBrains.Diagnostics.LogEx.Error(ILog this, Exception ex, String message)
     at JetBrains.Util.Logging.Logger.LogException(Exception ex)
     at JetBrains.Application.Components.InitializationStrategyDefault.Schedule(Lifetime lifetime, ICollection`1 dscs, IComponentContainer container)
     at JetBrains.Application.Components.ComponentStorage.ComposeDescriptors(ICollection`1 descriptors)
     at JetBrains.Application.Components.ComponentContainer.Compose()
     at JetBrains.Application.Components.FactoryComponentContainer.CreateInstanceCore(Lifetime lifetime, Type type, IComponentContainer parent, Object[] args)
     at JetBrains.Application.Components.FactoryComponentContainer.CreateInstance(Lifetime lifetime, Type objecttype, IComponentContainer parent, Object[] args)
     at JetBrains.Application.UI.Options.OptionsDialog.OptionsPageFactory.CreateOptionsPage(OptionsPageDescriptor pagedescriptor, IComponentContainer containerParent, OptionsSettingsSmartContext injectSettingsStoreSmartContext, IShellLocks locks)
     at JetBrains.Application.UI.Options.OptionsDialog.OptionsPageFactory.<>c__DisplayClass3_0.<CreateOptionsPage>b__1(OptionsPageDescriptor inlineChildDescriptor)
     at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
     at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
     at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
     at JetBrains.Application.UI.Options.OptionsDialog.OptionsPageFactory.CreateOptionsPage(OptionsPageDescriptor pagedescriptor, IComponentContainer containerParent, OptionsSettingsSmartContext injectSettingsStoreSmartContext, IShellLocks locks)
     at JetBrains.Application.UI.Options.OptionsDialog.OptionsPageInOptionsContextAutomation.GetOrCreateOptionsPage()
     at JetBrains.ReSharper.Host.Features.Settings.OptionsPage.OptionsPageHost.<>c__DisplayClass8_1.<SubscribeForDialog>b__10()
     at JetBrains.Threading.ReentrancyGuard.<>c__DisplayClass31_0.<Queue>b__0()
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     at JetBrains.Threading.ReentrancyGuard.ExecutePendingActions()
     at JetBrains.Threading.JetDispatcher.Closure.Execute()
     at JetBrains.Threading.JetDispatcher.Run()
     at JetBrains.ReSharper.Host.Product.RiderMain.Main(Lifetime lifetime, IRiderSettings settings, ILogger logger, ProtocolComponent protocol, RdShellModel shellModel, ApplicationShutdownRequests shutdownRequests)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at JetBrains.Application.Environment.RunsPublicStaticIntMain.<>c__DisplayClass0_0.<.ctor>b__0()
     at JetBrains.Application.Environment.RunsPublicStaticIntMain.<>c__DisplayClass0_2.<.ctor>b__5()
     at JetBrains.Util.Logging.Logger.Catch(Action action)
     at JetBrains.Application.Threading.IThreadingEx.<>c__DisplayClass18_1.<ExecuteOrQueueWhenNotGuarded>b__4()
     at JetBrains.Threading.JetDispatcher.Closure.Execute()
     at JetBrains.Threading.JetDispatcher.Run(Func`1 condition, TimeSpan timeout, Boolean bThrowOnTimeout)
     at JetBrains.Application.Environment.IJetHostEx.RunHostMessageLoop(IComponentContainer containerEnv)
     at JetBrains.Application.Environment.HostParameters.MessagePumpMainLoopHostMixin.JetBrains.Application.Environment.HostParameters.IRunMainLoopHostMixin.RunMainLoop(ComponentContainer containerEnv)
     at JetBrains.Application.Environment.HostParameters.JetHostParametersCaller.RunMainLoop(ComponentContainer containerEnv)
     at JetBrains.Application.Environment.JetEnvironment.InternalRun(JetHostParametersCaller host, ComponentContainer containerEnv)
     at JetBrains.Application.Environment.JetEnvironment.CreateAndRun(Full hostparams)
     at JetBrains.Application.Environment.JetHostItems.CreateAndRun(Full input)
     at JetBrains.ReSharper.Host.Product.RiderBackendProgram.MainX(Assembly assembly, HostInfo hostInfo, String[] args)
     at JetBrains.ReSharper.Host.Product.RiderBackendProgram.<>c.<Main>b__3_0(Lifetime lifetime)
     at JetBrains.Lifetimes.Lifetime.Using[T](Func`2 action)
     at JetBrains.ReSharper.Host.Product.RiderBackendProgram.Main()
”
```

Looks like the `GetNewEntry()` method should be implemented in `MockAliasesModel`.

(Sadly, this API contract was changed several times during 2021.1 development)

**Comment by Socolin** [comment]
Thanks for the report,

This should be be fixed with next version (1.4.1.) that will be available soon
